# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.terra_user import TerraUser
from .user_get_info_for_user_id_response_is_authenticated import UserGetInfoForUserIdResponseIsAuthenticated

UserGetInfoForUserIdResponse = typing.Union[UserGetInfoForUserIdResponseIsAuthenticated, typing.List[TerraUser]]
