# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...types.terra_user import TerraUser
from .user_get_info_for_user_id_response_is_authenticated_status import (
    UserGetInfoForUserIdResponseIsAuthenticatedStatus,
)


class UserGetInfoForUserIdResponseIsAuthenticated(UncheckedBaseModel):
    """
    User information for one connection (single User object)
    """

    user: typing.Optional[TerraUser] = None
    status: typing.Optional[UserGetInfoForUserIdResponseIsAuthenticatedStatus] = None
    is_authenticated: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
