# This file was auto-generated by Fern from our API Definition.

import typing

from .user_get_all_user_i_ds_response_data import UserGetAllUserIDsResponseData
from .user_get_all_user_i_ds_response_users import UserGetAllUserIDsResponseUsers

UserGetAllUserIDsResponse = typing.Union[UserGetAllUserIDsResponseUsers, UserGetAllUserIDsResponseData]
