# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.data_sent_to_webhook import DataSentToWebhook
from ...types.large_request_processing_event import LargeRequestProcessingEvent
from ...types.no_data_returned import NoDataReturned
from ...types.rate_limit_request_processing import RateLimitRequestProcessing
from ...types.request_processing import RequestProcessing
from .nutrition_fetch_response_data import NutritionFetchResponseData

NutritionFetchResponse = typing.Union[
    NutritionFetchResponseData,
    NoDataReturned,
    DataSentToWebhook,
    RequestProcessing,
    RateLimitRequestProcessing,
    LargeRequestProcessingEvent,
]
