# This file was auto-generated by Fern from our API Definition.

import typing

DeviceDataType = typing.Union[
    typing.Literal[
        "STEPS",
        "ACTIVE_MINUTES",
        "BMR",
        "CALORIES",
        "DISTANCE",
        "HEART_RATE",
        "OXYGEN_SATURATION",
        "SLEEP_TYPE",
        "SPEED",
        "CADENCE",
    ],
    typing.Any,
]
