# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .distance_data_detailed import DistanceDataDetailed
from .distance_data_summary import DistanceDataSummary


class DistanceData(UncheckedBaseModel):
    detailed: typing.Optional[DistanceDataDetailed] = pydantic.Field(default=None)
    """
    Object containing detailed distance information - this may included second-by-second samples.
    """

    summary: typing.Optional[DistanceDataSummary] = pydantic.Field(default=None)
    """
    Object containing summary information related to distance covered throughout the workout.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
