# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .inconclusive import Inconclusive
from .raw_ecg_sample import RawEcgSample


class EcgReading(UncheckedBaseModel):
    start_timestamp: str
    avg_hr_bpm: float
    afib_classification: Inconclusive
    raw_signal: typing.List[RawEcgSample]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
