# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .heart_rate_data_detailed import HeartRateDataDetailed
from .heart_rate_data_summary import HeartRateDataSummary


class HeartRateData(UncheckedBaseModel):
    detailed: typing.Optional[HeartRateDataDetailed] = pydantic.Field(default=None)
    """
    Object containing detailed heart rate information for the associated workout.
    """

    summary: typing.Optional[HeartRateDataSummary] = pydantic.Field(default=None)
    """
    Object containing summary heart rate information for the associated workout.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
