# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .hydration_measurement_sample import HydrationMeasurementSample


class HydrationData(UncheckedBaseModel):
    day_total_water_consumption_ml: typing.Optional[float] = pydantic.Field(default=None)
    """
    User's total water consumption throughout the day.
    """

    hydration_amount_samples: typing.Optional[typing.List[HydrationMeasurementSample]] = pydantic.Field(default=None)
    """
    User's hydration level samples throughout the day.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
