# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class IntegrationProviderTypes(UncheckedBaseModel):
    """
    Indicates the types of data available through the provider
    """

    activity: typing.Optional[bool] = None
    body: typing.Optional[bool] = None
    nutrition: typing.Optional[bool] = None
    daily: typing.Optional[bool] = None
    sleep: typing.Optional[bool] = None
    menstruation: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
