# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .stroke_type import StrokeType


class LapSample(UncheckedBaseModel):
    start_time: str
    end_time: str
    distance_meters: float
    calories: float
    total_strokes: int
    stroke_type: StrokeType
    avg_speed_meters_per_second: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
