# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .measurement_data_sample import MeasurementDataSample


class MeasurementsData(UncheckedBaseModel):
    measurements: typing.Optional[typing.List[MeasurementDataSample]] = pydantic.Field(default=None)
    """
    List of body metrics & measurements taken throughout the associated day.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
