# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .menstruation_data import MenstruationData
from .menstruation_metadata import MenstruationMetadata


class Menstruation(UncheckedBaseModel):
    metadata: MenstruationMetadata = pydantic.Field()
    """
    Object containing daily summary metadata.
    """

    menstruation_data: typing.Optional[MenstruationData] = pydantic.Field(default=None)
    """
    Object containing information on user's menstruation for a given day.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
