# This file was auto-generated by Fern from our API Definition.

import typing

PacePlannedWorkoutStepTargetTargetType = typing.Union[
    typing.Literal[
        "SPEED",
        "HEART_RATE",
        "OPEN",
        "CADENCE",
        "POWER",
        "GRADE",
        "RESISTANCE",
        "POWER_LAP",
        "SWIM_STROKE",
        "SPEED_LAP",
        "HEART_RATE_LAP",
        "PACE",
        "HEART_RATE_THRESHOLD_PERCENTAGE",
        "HEART_RATE_MAX_PERCENTAGE",
        "SPEED_PERCENTAGE",
        "POWER_PERCENTAGE",
        "REPETITION",
        "TSS",
        "IF",
    ],
    typing.Any,
]
