# This file was auto-generated by Fern from our API Definition.

import typing

PlannedWorkoutStepIntensity = typing.Union[
    typing.Literal["REST", "WARMUP", "COOLDOWN", "RECOVERY", "INTERVAL", "ACTIVE"], typing.Any
]
