# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .planned_workout_metadata import PlannedWorkoutMetadata
from .planned_workout_steps import PlannedWorkoutSteps


class PlannedWorkout(UncheckedBaseModel):
    steps: typing.Optional[typing.List[PlannedWorkoutSteps]] = pydantic.Field(default=None)
    """
    List of exercises/steps/intervals for the workout plan
    """

    metadata: typing.Optional[PlannedWorkoutMetadata] = pydantic.Field(default=None)
    """
    Metadata for the workout plan
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
