# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .repetition_planned_workout_step_target_target_type import RepetitionPlannedWorkoutStepTargetTargetType


class RepetitionPlannedWorkoutStepTarget(UncheckedBaseModel):
    target_type: typing.Optional[RepetitionPlannedWorkoutStepTargetTargetType] = pydantic.Field(default=None)
    """
    Type of target for the workout - i.e. metric type for which a criterion must be met for the workout to be completed
    """

    repetitions: typing.Optional[float] = pydantic.Field(default=None)
    """
    Number of repetitions of the workout step to be performed
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
