# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ScoresData(UncheckedBaseModel):
    activity: typing.Optional[float] = pydantic.Field(default=None)
    """
    Activity score for the given day.
    """

    recovery: typing.Optional[float] = pydantic.Field(default=None)
    """
    Recovery score for the given day.
    """

    sleep: typing.Optional[float] = pydantic.Field(default=None)
    """
    Sleep score for the given day, pertaining to the previous night's sleep.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
