# This file was auto-generated by Fern from our API Definition.

import typing

SwimmingPlannedWorkoutStepEquipementType = typing.Union[
    typing.Literal["NONE", "SWIM_FINS", "SWIM_KICKBOARD", "SWIM_PADDLES", "SWIM_PULL_BUOY", "SWIM_SNORKEL"], typing.Any
]
