# This file was auto-generated by Fern from our API Definition.

import typing

SwimmingPlannedWorkoutStepStrokeType = typing.Union[
    typing.Literal["OTHER", "FREESTYLE", "BACKSTROKE", "BREASTSTROKE", "BUTTERFLY", "REST"], typing.Any
]
