# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .tss_sample import TssSample


class TssData(UncheckedBaseModel):
    tss_samples: typing_extensions.Annotated[
        typing.Optional[typing.List[TssSample]], FieldMetadata(alias="TSS_samples")
    ] = pydantic.Field(default=None)
    """
    Array of TSS information sampled throughout the workout
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
