# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class TssSample(UncheckedBaseModel):
    planned: typing.Optional[float] = None
    actual: typing.Optional[float] = None
    method: typing.Optional[str] = None
    intensity_factor_planned: typing.Optional[float] = None
    intensity_factor_actual: typing.Optional[float] = None
    normalized_power_watts: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
