# This file was auto-generated by Fern from our API Definition.

import typing

from .access_revoked_event import AccessRevokedEvent
from .activity_event import ActivityEvent
from .athlete_event import AthleteEvent
from .auth_error_event import AuthErrorEvent
from .auth_success_event import AuthSuccessEvent
from .body_event import BodyEvent
from .connection_error_event import ConnectionErrorEvent
from .daily_event import DailyEvent
from .deauth_event import DeauthEvent
from .google_no_datasource_event import GoogleNoDatasourceEvent
from .healthcheck_event import HealthcheckEvent
from .large_request_processing_event import LargeRequestProcessingEvent
from .large_request_sending_event import LargeRequestSendingEvent
from .menstruation_event import MenstruationEvent
from .nutrition_event import NutritionEvent
from .permission_change_event import PermissionChangeEvent
from .processing_event import ProcessingEvent
from .rate_limit_hit_event import RateLimitHitEvent
from .s_3_payload_event import S3PayloadEvent
from .sleep_event import SleepEvent
from .user_reauth_event import UserReauthEvent

WebhookEventType = typing.Union[
    HealthcheckEvent,
    AuthSuccessEvent,
    AuthErrorEvent,
    DeauthEvent,
    UserReauthEvent,
    AccessRevokedEvent,
    ConnectionErrorEvent,
    GoogleNoDatasourceEvent,
    PermissionChangeEvent,
    ProcessingEvent,
    LargeRequestProcessingEvent,
    LargeRequestSendingEvent,
    RateLimitHitEvent,
    ActivityEvent,
    AthleteEvent,
    BodyEvent,
    DailyEvent,
    MenstruationEvent,
    NutritionEvent,
    SleepEvent,
    S3PayloadEvent,
]
