# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .authentication_authenticate_user_response_status import AuthenticationAuthenticateUserResponseStatus


class AuthenticationAuthenticateUserResponse(UncheckedBaseModel):
    status: typing.Optional[AuthenticationAuthenticateUserResponseStatus] = pydantic.Field(default=None)
    """
    indicates that the request was successful
    """

    user_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    User ID for the user being created
    """

    auth_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    authentication URL the user must be redirected to in order to link their account
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
