# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .authentication_generate_widget_session_response_status import AuthenticationGenerateWidgetSessionResponseStatus


class AuthenticationGenerateWidgetSessionResponse(UncheckedBaseModel):
    session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Session ID for the widget authentication session
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    the widget URL the user must be redirected to in order to link their account
    """

    status: typing.Optional[AuthenticationGenerateWidgetSessionResponseStatus] = pydantic.Field(default=None)
    """
    indicates that the request was successful (value is success)
    """

    expires_in: typing.Optional[float] = pydantic.Field(default=None)
    """
    a number in seconds depicting how long the url is valid for
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
